#!/bin/bash

# Laptop
DISP0="LVDS1"
MODE0="1366x768"
# 23inch monitor
DISP1="HDMI1"
MODE1="1920x1080"

if [ -n "$1" ]
then
    case ${1} in
        d|default) DEFAULT=1 ;;
	s|sala) xrandr --output HDMI1 --mode 1366x768 --output LVDS1 --mode 1366x768 --same-as HDMI1 ; exit 0 ;;
	*) echo "Dafuq?" ; exit 1 ;;
    esac
fi

chdis()
{
    xrandr --output ${1} --off --output ${2} --mode ${3}
    sed -i '/minimum_size/s/ [0-9]*/ '${3%%x*}'/' ${HOME}/.config/conky/conkyrc
}

if [ "`xrandr -q | sed -n '/'"$DISP1"'/s/ [0-9(].*//p'`" = "$DISP1 connected" ] && [ -z "$DEFAULT" ]
then
    chdis ${DISP0} ${DISP1} ${MODE1}
else
    chdis ${DISP1} ${DISP0} ${MODE0}
fi

sleep 1

for ID in `xprop -root -notype _NET_CLIENT_LIST | sed 's/.*# //'`
do
    case `xprop -id "$ID" -notype WM_CLASS | sed 's/.*"\([^"]*\)"/\1/'` in
        URxvt|Firefox|Iceweasel|Google*|libreoffice*) 
            for ACTION in remove add
	    do
	        wmctrl -ir ${ID} -b ${ACTION},maximized_vert,maximized_horz
	    done
        ;;
    esac
done
