#!/bin/bash
#
# Screenshots with scrot

DIRC="/tmp/captures"
IMGN=`date +%s.png`

[ ! -d ${DIRC} ] && mkdir ${DIRC}

if [ -z "$1" ]
then
    scrot -s ${DIRC}/${IMGN}
else
    scrot ${DIRC}/${IMGN}
fi

notify-send "CAPTURE" "Saved as $IMGN"
