#!/bin/bash

DIRC="/tmp/captures"
IMGN=`date +%s.png`

[ ! -d ${DIRC} ] && mkdir ${DIRC}

if [ -z "$1" ]
then
    scrot -s ${DIRC}/${IMGN}
else
    if [ `uname -s` = "Linux" ]
    then
        mtpaint -s
    else
        scrot ${DIRC}/${IMGN}
    fi
fi

notify-send "CAPTURE" "Saved as $IMGN"
