#!/bin/bash
#
# Download source file for slackbuilds script

INFO=`/bin/ls -1 *info 2> /dev/null`
if [ "$?" -gt 0 ]
then
    echo "There isn't an info file."
    exit 1
fi

down(){ for FILE in ${@} ; do wget --timeout=20 --tries=2 --passive-ftp -c ${FILE} ; done ; }

. ${INFO}

if [ `uname -m` = "x86_64" ] && [ -n "$DOWNLOAD_x86_64" ]
then
    down ${DOWNLOAD_x86_64}
else
    down ${DOWNLOAD}
fi
