#!/bin/bash
#
# Download source file for slackbuilds script

INFO=`/bin/ls -1 *info 2> /dev/null`
if [ "$?" -gt 0 ]
then
    echo "There isn't an info file."
    exit 1
fi

DOWN32=`sed -n 's/DOWNLOAD="\([^"]*\)"/\1/p' ${INFO}`
DOWN64=`sed -n 's/DOWNLOAD_x86_64="\([^"]*\)"/\1/p' ${INFO}`

if [ `uname -m` = "x86_64" ] && [ -n "$DOWN64" ]
then
    wget ${DOWN64}
else
    wget ${DOWN32}
fi
