#!/bin/bash

CONFDIR=/home/vando/.getmail

if [ -z "`pgrep -d, -x getmail`" ]
then
    for FILE in ${CONFDIR}/rc-*
    do
        RCFILES="$RCFILES -r $FILE"
    done

    getmail ${RCFILES} ${@} 2> /tmp/getmail-err.log
fi
