#!/bin/bash

pkill -HUP -x ssh
pkill -HUP -x getmail

if [ "`xrandr -q | sed -n '/HDMI/s/ [0-9].*//p'`" = "HDMI1 connected" ]
then
    86display default
    sleep 3
fi

if [ `uname -s` = "Linux" ]
then
    if [ -s /etc/debian_version ]
    then
	sudo systemctl hibernate &
    else
        sudo /usr/sbin/pm-hibernate &
    fi
else
    /usr/sbin/zzz -Z &
fi

xlock
