#!/bin/bash

pkill -HUP -x ssh
ssh-add -D

if [ "`xrandr -q | sed -n '/HDMI/s/ [0-9].*//p'`" = "HDMI1 connected" ]
then
    86display default
    sleep 3
fi

while pgrep -x getmail > /dev/null
do
    sleep 2
done

if [ `uname -s` = "Linux" ]
then
    sudo /usr/sbin/pm-hibernate &
else
    /usr/sbin/zzz -Z &
fi

xlock
