#!/bin/sh

# This script runs on OpenWRT and uses FreeDNS service
# https://freedns.afraid.org

TOKEN=
DOMAIN=
DNS=${DNS:-208.67.222.222}

if [ -z "$TOKEN" ] || [ -z "$DOMAIN" ]
then
    exit 1
fi

if [ `uci -P /var/state get network.wan.up` != 1 ]
then
    /etc/init.d/network restart
    exit 1
fi

IP=`uci -P /var/state get network.wan.ipaddr`

if [ "$IP" != `uci -P /var/state get network.wan.lastipaddr` ]
then
   wget -qO /dev/null ${TOKEN}

   # Got freeDNS my new IP? Ask to a DNS provider
   sleep 10
   if [ `nslookup ${DOMAIN} ${DNS} | sed -n 's/.*: \([^ ]*\) .*/\1/p'` == "$IP" ]
   then
      date "+%Y%m%d %R  $IP" >> /var/log/ip.log
      uci -P /var/state set network.wan.lastipaddr="$IP"
   fi
fi
