#!/bin/bash

pkill -HUP -f "ssh "
ssh-add -D

xlock & 
sleep 3

while pgrep -f getmail > /dev/null
do
    sleep 2
done

if [ `uname -s` = "Linux" ]
then
    sudo /usr/sbin/pm-hibernate
else
    /usr/sbin/zzz -Z
fi
